---
title: "Informative Prior Distributions for non-clinical Populations"
header-includes:
   - \usepackage{placeins}
output: pdf_document
---

```{r loading packages, message=FALSE, warning=FALSE, include=FALSE}
rm(list = ls())
source("helpers.R")

set.seed(1234)
load(file = "../data/DDM_cleaned_non_clinical.RData")
```


#  Fitting one distribution
\FloatBarrier
## Drift Rate

```{r Drift Rate, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow = c(1, 2))
drift_normal <- fit_trunc_Normal(abs(v$v),
                                 lower = 0, upper = Inf, mean = 1.3,
                                 sd = 1,
                                 bins = 80)
drift_t <- fit_trunc_t(estimate = abs(v$v), location = mean(abs(v$v)),
                       df =1 , scale = sd(v$v), lower = 0, upper = Inf)
drift_gamma <- fit_Gamma(estimate = abs(v$v))
drift_log <- fit_log(estimate = abs(v$v))
drift_weibull <- fit_weibull(estimate = abs(v$v))

par(mfrow = c(1, 1))

drift_compare_one <- round(cbind(AIC(drift_normal), AIC(drift_t),
                                    AIC(drift_gamma), AIC(drift_log), AIC(drift_weibull)), 2)
drift_compare_one <- data.frame(rbind(c("truncated normal", "t", "gamma", "lognormal", "weibull"), drift_compare_one))


```

```{r Fitting mixture mirrored Drift Rate, message=FALSE, warning=FALSE, include=FALSE}

drift_mix_tnorm <- mix_tnorm(estimate = abs(v$v), mean = mean(abs(v$v)),
                            sd =  sd(abs(v$v) ), mean1 = 1, sd1 = 2,
                            prob = 0.5,
                            txt = "Drift rate: mixture nomal")
drift_mix_gamma <- mix_gamma(estimate = abs(v$v),
                             shape = 1.530, rate = 0.598,
                             shape1 = 2 , rate1 = 1, prob = 0.5, txt = "Drift: mixture gamma")

drift_mix_gamma_tnorm <- mix_gamma_tnorm(abs(v$v),
                                         mean = mean(abs(v$v)),
                                         sd = sd(abs(v$v)), shape = 9, rate = 5,
                                         prob = 0.5, txt = "Drift rate: mixture gamma and tnorm")

drift_mix_lognormal_tnorm <- mix_ln_tnorm(abs(v$v),
                                          mean = mean(abs(v$v)),
                                         sd = sd(abs(v$v)),
                                         meanlog = 0, sdlog = sd(v$v), prob = 0.3,
                                         txt = "Drift: Mixture lognormal and normal")

drift_mix_comp <- round(data.frame(cbind(drift_mix_tnorm$AIC, drift_mix_gamma$AIC,
                                         drift_mix_gamma_tnorm$AIC, 
                                         drift_mix_lognormal_tnorm$AIC)), 2)
drift_mix_comp <- rbind(c("tnorm & tnorm", "gamma & gamma", "gamma & tnorm",
                             "lognormal & tnorm"), drift_mix_comp)

drift_compare <- cbind(drift_compare_one, drift_mix_comp)
kable(drift_compare, caption = "Drift: Model Selection")

```

\FloatBarrier

## Boundary Separation

```{r Fitting Boundary Separation, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow = c(3, 2))
boundary_normal <- fit_trunc_Normal(estimate = a$a, mean = 2, sd = 0.9, bins = 80, lower = 0, upper = Inf)
boundary_t <- fit_trunc_t(a$a, location = 2, scale = 0.5, df = 3, lower = 0, upper = Inf)
boundary_gamma <- fit_Gamma(estimate = a$a[a$a >0])
boundary_log <- fit_log(estimate = a$a[a$a >0])
boundary_weibull <- fit_weibull(estimate = a$a[a$a >0])
par(mfrow = c(1, 1))

boundary_compare_one <- round(cbind(AIC(boundary_normal), AIC(boundary_t),
                                    AIC(boundary_gamma), AIC(boundary_log), AIC(boundary_weibull)), 2)
boundary_compare_one <- data.frame(rbind(c("truncated normal", "t", "gamma", "lognormal", "weibull"), boundary_compare_one))

```

```{r Fitting mixture Boundary Separation, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow = c(2,2))
boundary_mix_tnorm <- mix_tnorm(estimate = a$a,
                                mean = mean(a$a),
                                sd =  sd(a$a), mean1 = mean(a$a), sd1 = 0.5, prob = 0.5,
                                txt = "Boundary: mixture nomal")

boundary_mix_gamma <- mix_gamma(estimate = a$a,
                             shape = 1.530, rate = 0.598,
                             shape1 = 2 , rate1 = 1, prob = 0.5, txt = "Boundary: mixture gamma")

boundary_mix_gamma_tnorm <- mix_gamma_tnorm(a$a,
                                         mean = mean(a$a),
                                         sd = sd(a$a), shape = 9, rate = 5,
                                         prob = 0.5, txt = "Boundary rate: mixture gamma and tnorm")

boundary_mix_lognormal_tnorm <- mix_ln_tnorm(a$a,
                                          mean = mean(a$a),
                                         sd = sd(a$a),
                                         meanlog = 0, sdlog = sd(a$a), prob = 0.3,
                                         txt = "Boundary: Mixture lognormal and normal")
par(mfrow = c(1,1))

boundary_mix_comp <- round(data.frame(cbind(boundary_mix_tnorm$AIC, boundary_mix_gamma$AIC,
                                         boundary_mix_gamma_tnorm$AIC, 
                                         boundary_mix_lognormal_tnorm$AIC)), 2)
boundary_mix_comp <- rbind(c("tnorm & tnorm", "gamma & gamma", "gamma & tnorm",
                             "lognormal & tnorm"), boundary_mix_comp)

boundary_compare <- cbind(boundary_compare_one, boundary_mix_comp)
kable(boundary_compare, caption = "Boundary Separation: Model Selection")
```

\FloatBarrier
## Mirrored Bias

```{r Mirrored Bias, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow = c(3, 2))
mirrored_bias_normal <- fit_trunc_Normal(estimate = zr_mirrored, mean = 0.5, sd = 0.2, bins = 80, lower = 0, upper = 1)
mirrored_bias_t <- fit_trunc_t_bias(zr_mirrored, location = 1, scale = 2, lower = 0, upper = 1, df =2)

mirrored_bias_compare_one <- round(cbind(AIC(mirrored_bias_normal), AIC(mirrored_bias_t)), 2)
mirrored_bias_compare_one <- data.frame(rbind(c("truncated normal", " truncated t"), mirrored_bias_compare_one))

```
\FloatBarrier

## Non-decision time

```{r Fitting ter, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow = c(3, 2))
ter_normal <- fit_trunc_Normal(estimate = ter$ter, mean = mean(ter$ter), sd = sd(ter$ter), bins = 100, lower = 0, upper = Inf)
ter_t <- fit_trunc_t(estimate = ter$ter, location = 1, scale = 1, df=3, lower = 0, upper = Inf)
ter_gamma <- fit_Gamma(estimate = ter$ter[which(ter$ter > 0)])
ter_log <- fit_log(estimate = ter$ter[which(ter$ter > 0)])
ter_weibull <- fit_weibull(estimate = ter$ter[which(ter$ter > 0)])
par(mfrow = c(1, 1))

ter_compare_one <- round(cbind(AIC(ter_normal), AIC(ter_t),
                                    AIC(ter_gamma), AIC(ter_log),
                                AIC(ter_weibull)), 2)
ter_compare_one <- data.frame(rbind(c("truncated normal", "t", "gamma", "lognormal", "weibull"), ter_compare_one))

```

```{r Fitting mixture ter, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow = c(2,2))
ter_mix_tnorm <- mix_tnorm(estimate = ter$ter[which(ter$ter > 0)],
                           mean = mean(ter$ter),
                           sd =  0.2,
                           mean1 = 0.3, sd1 = sd(ter$ter), prob = 0.5,
                           txt = "Ter: mixture nomal")

ter_mix_gamma <- mix_gamma(estimate = ter$ter[which(ter$ter > 0)],
                             shape = 60, rate = 10,
                             shape1 = 10 , rate1 = 15, prob = 0.5, txt = "Ter: mixture gamma")

ter_mix_gamma_tnorm <- mix_gamma_tnorm(ter$ter[which(ter$ter > 0)],
                                       mean = 0.4,
                                       sd = 0.35, shape = 5, rate = 12,
                                       prob = 0.2, txt = "Ter: mixture gamma and tnorm")

ter_mix_lognormal_tnorm <- mix_ln_tnorm(ter$ter[which(ter$ter > 0)],
                                          mean = 0.4,
                                         sd = 0.3,
                                         meanlog = log(mean(ter$ter)), 
                                        sdlog = log(sd(ter$ter)), prob = 0.4,
                                         txt = "Ter: Mixture lognormal and normal")
par(mfrow = c(1,1))

ter_mix_comp <- round(data.frame(cbind(ter_mix_tnorm$AIC, ter_mix_gamma$AIC,
                                         ter_mix_gamma_tnorm$AIC, 
                                         ter_mix_lognormal_tnorm$AIC)), 2)
ter_mix_comp <- rbind(c("tnorm & tnorm", "gamma & gamma", "gamma & tnorm",
                             "lognormal & tnorm"), ter_mix_comp)

ter_compare <- cbind(ter_compare_one, ter_mix_comp)
kable(ter_compare, caption = "ter: Model Selection")

```
\FloatBarrier

## sv

```{r Fitting sv, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow = c(3, 2))
sv_normal <- fit_trunc_Normal(estimate = sv$sv, mean = 1.4, sd = 1, bins = 100, lower = 0, upper = Inf)
sv_t <- fit_trunc_t(estimate = sv$sv[sv$sv>=0], location = 1, scale = 0.2,
                    df =3, lower = 0, upper = Inf)
sv_gamma <- fit_Gamma(estimate = sv$sv[sv$sv>0])
sv_log <- fit_log(estimate =sv$sv[sv$sv>0])
sv_weibull <- fit_weibull(estimate = sv$sv[sv$sv>0])
par(mfrow = c(1, 1))

sv_compare_one <- round(cbind(AIC(sv_normal), AIC(sv_t),
                                    AIC(sv_gamma), AIC(sv_log),
                                AIC(sv_weibull)), 2)
sv_compare_one <- data.frame(rbind(c("truncated normal", "t", "gamma", "lognormal", "weibull"), sv_compare_one))

```

```{r Fitting mixture sv, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow = c(2,2))
sv_mix_tnorm <- mix_tnorm(estimate = sv$sv[sv$sv > 0],
                                mean = mean(sv$sv),
                               sd =  sd(sv$sv), mean1 = 1, sd1 = 0.6, prob = 0.7,
                               txt = "sv: mixture nomal")

sv_mix_gamma <- mix_gamma(estimate = sv$sv[sv$sv > 0],
                             shape = 1, rate = 3,
                             shape1 = 2 , rate1 =  10, prob = 0.5, txt = "sv: mixture gamma")

sv_mix_gamma_tnorm <- mix_gamma_tnorm(sv$sv[sv$sv > 0],
                                         mean = mean(sv$sv),
                                         sd = sd(sv$sv), shape = 1, rate = 1,
                                         prob = 0.3, txt = "sv: mixture gamma and tnorm")

sv_mix_lognormal_tnorm <- mix_ln_tnorm(sv$sv[sv$sv > 0],
                                          mean = mean(sv$sv),
                                         sd = sd(sv$sv),
                                         meanlog = 0.5, sdlog = 0.3, prob = 0.2,
                                         txt = "sv: Mixture lognormal and normal")
par(mfrow = c(1,1))

sv_mix_comp <- round(data.frame(cbind(sv_mix_tnorm$AIC, sv_mix_gamma$AIC,
                                         sv_mix_gamma_tnorm$AIC, 
                                         sv_mix_lognormal_tnorm$AIC)), 2)
sv_mix_comp <- rbind(c("tnorm & tnorm", "gamma & gamma", "gamma & tnorm",
                             "lognormal & tnorm"), sv_mix_comp)

sv_compare <- cbind(sv_compare_one, sv_mix_comp)
kable(sv_compare, caption = "sv: Model Selection")
```
\FloatBarrier

## relative sz
```{r Fitting relative sz, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow = c(3, 2))
rel_sz_normal <- fit_trunc_Normal(estimate = sz_relative$sz_relative, mean = 0.7, sd = 0.5, bins = 100, lower = 0, upper = 1)
rel_sz_t <- fit_trunc_t(estimate = sz_relative$sz_relative, location = 0.5, scale = 1, df = 2, lower = 0, upper = 1)

rel_sz_compare_one <- round(cbind(AIC(rel_sz_normal), AIC(rel_sz_t)), 2)
rel_sz_compare_one <- data.frame(rbind(c("truncated normal", "t"), rel_sz_compare_one))

```
\FloatBarrier


## ster

```{r Fitting ster, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow = c(3, 2))
st_normal <- fit_trunc_Normal(estimate = ster$ster, mean = 0.3, sd = 0.5, bins = 100,
                              lower = 0, upper = Inf)
st_t <- fit_trunc_t(estimate = ster$ster, location = 0.3, scale = 1, df = 2, lower = 0, upper = Inf)
st_gamma <- fit_Gamma(estimate = ster$ster[ster$ster > 0])
st_log <- fit_log(estimate = ster$ster[ster$ster > 0])
st_weibull <- fit_weibull(estimate = ster$ster[ster$ster> 0])
par(mfrow = c(1, 1))

ster_compare_one <- round(cbind(AIC(st_normal), AIC(st_t),
                                    AIC(st_gamma), AIC(st_log),
                                AIC(st_weibull)), 2)
ster_compare_one <- data.frame(rbind(c("truncated normal", "t", "gamma", "lognormal", "weibull"), ster_compare_one))

```

```{r Fitting mixture ster, message=FALSE, warning=FALSE, include=FALSE}
par(mfrow = c(2,2))
st_mix_tnorm <- mix_tnorm(estimate = ster$ster[which(ster$ster > 0)],
          mean = -13,
          sd =  2, mean1 = 0.2,
          sd1 = 0.01, prob = 0.5,
          txt = "ster: mixture nomal")

st_mix_gamma <- mix_gamma(estimate = ster$ster[ster$ster>0],
                             shape = 1, rate = 1,
                             shape1 = 2 , rate1 = 9, prob = 0.5, txt = "ster: mixture gamma")

st_mix_gamma_tnorm <- mix_gamma_tnorm(ster$ster[ster$ster>0],
                mean = -13,
                sd = 2, shape = 10, rate = 60,
                prob = 0.5, txt = "ster: mixture gamma and tnorm")

st_mix_lognormal_tnorm <- mix_ln_tnorm(ster$ster[ster$ster>0],
                                          mean = 0.17,
                                         sd = 0.05,
                                         meanlog = -2,
                                       sdlog = 1.5, prob = 0.6,
                                         txt = "ster: Mixture lognormal and normal")
par(mfrow = c(1,1))

st_mix_comp <- round(data.frame(cbind(st_mix_tnorm$AIC, st_mix_gamma$AIC,
                                         st_mix_gamma_tnorm$AIC, 
                                         st_mix_lognormal_tnorm$AIC)), 2)
st_mix_comp <- rbind(c("tnorm & tnorm", "gamma & gamma", "gamma & tnorm",
                             "lognormal & tnorm"), st_mix_comp)

ster_compare <- cbind(ster_compare_one, st_mix_comp)

kable(ster_compare, caption = "st: Model Selection")

```

# Model Selection: Representative distributions

```{r Priors, message=FALSE, warning=FALSE, include=FALSE}

drift_compare <- as.data.frame(t(drift_compare))
drift_compare[, 1] <- as.character(drift_compare[, 1])
drift_compare[, 2] <- as.numeric(drift_compare[, 2])
drift_compare$waic <- round(wAIC(drift_compare[, 2])$weights, 2)
drift_compare_final <- drift_compare[which.min(drift_compare$V2), ]

boundary_compare <- as.data.frame(t(boundary_compare))
boundary_compare[, 1] <- as.character(boundary_compare[, 1])
boundary_compare$V2<- as.numeric(as.character(boundary_compare$V2))
boundary_compare$wAIC <- round(wAIC(boundary_compare[, 2])$weights, 2)
boundary_compare_final <- boundary_compare[which.min(boundary_compare$V2), ]

mirrored_bias_compare <- as.data.frame(t(mirrored_bias_compare_one))
mirrored_bias_compare[, 1] <- as.character(mirrored_bias_compare[, 1])
mirrored_bias_compare[, 2] <- as.numeric(as.character(mirrored_bias_compare[, 2]))
mirrored_bias_compare$wAIC <- round(wAIC(mirrored_bias_compare[, 2])$weights, 2)
mirrored_bias_compare_final <- mirrored_bias_compare[which.min(mirrored_bias_compare$V2), ]

ter_compare <- as.data.frame(t(ter_compare))
ter_compare[, 1] <- as.character(ter_compare[, 1])
ter_compare[, 2] <- as.numeric(as.character(ter_compare[, 2]))
ter_compare$wAIC <- round(wAIC(ter_compare[, 2])$weights, 2)
ter_compare_final <- ter_compare[which.min(ter_compare$V2), ]

sv_compare <- as.data.frame(t(sv_compare))
sv_compare[, 1] <- as.character(sv_compare[, 1])
sv_compare[, 2] <- as.numeric(as.character(sv_compare[, 2]))
sv_compare$wAIC <- round(wAIC(sv_compare[, 2])$weights, 2)
sv_compare_final <- sv_compare[which.min(sv_compare$V2), ]

relative_sz_compare <- as.data.frame(t(rel_sz_compare_one))
relative_sz_compare[, 1] <- as.character(relative_sz_compare[, 1])
relative_sz_compare[, 2] <- as.numeric(as.character(relative_sz_compare[, 2]))
relative_sz_compare$wAIC <- round(wAIC(relative_sz_compare[, 2])$weights, 2)
relative_sz_compare_final <- relative_sz_compare[which.min(relative_sz_compare$V2), ]

ster_compare <- as.data.frame(t(ster_compare))
ster_compare[, 1] <- as.character(as.character(ster_compare[, 1]))
ster_compare[, 2] <- as.numeric(as.character(ster_compare[, 2]))
ster_compare$wAIC <- round(wAIC(ster_compare[, 2])$weights, 2)
ster_compare_final <- ster_compare[which.min(ster_compare$V2), ]

```


```{r save data, message=FALSE, warning=FALSE, include=FALSE}

parameter_distributions <- list(
  v = list(
    distribution = drift_compare_final,
    mixing = drift_mix_gamma$par$estimate["prob"],
    shape = round(drift_mix_gamma$par$estimate["shape"], 2),
    rate = round(drift_mix_gamma$par$estimate["rate"], 2)
  ),
  a = list(
    distribution = boundary_compare_final,
    mixing = round(boundary_mix_gamma$par$estimate["prob"], 2),
    mean = round(boundary_mix_lognormal_tnorm$par$estimate["mean"], 2),
    sd = round(boundary_mix_lognormal_tnorm$par$estimate["sd"], 2)
  ),
   zr_mirrored = list(
     distribution = mirrored_bias_compare_final,
     location = round(mirrored_bias_t$estimate["location"], 2),
     scale = round(mirrored_bias_t$estimate["scale"], 2),
     df = round(mirrored_bias_t$estimate["df"], 2)
  ),
  ter = list(
    distribution = ter_compare_final,
    mixing = round(ter_mix_gamma$par$estimate["prob"], 2),
    shape = round(ter_mix_gamma$par$estimate["shape1"], 2),
    rate = round(ter_mix_gamma$par$estimate["rate1"], 2)
  ),
  sv = list(
    distribution = sv_compare_final,
    mixing = round(sv_mix_gamma_tnorm$par$estimate["prob"], 2),
    mean = round(sv_mix_gamma_tnorm$par$estimate["mean"], 2),
    sd = round(sv_mix_gamma_tnorm$par$estimate["sd"], 2)
  ),
  relative_sz = list(
    distribution = relative_sz_compare_final,
    mean = round(rel_sz_normal$estimate["mean"], 2),
    sd = round(rel_sz_normal$estimate["sd"], 2)
  ),
  ster = list(
    distribution = ster_compare_final,
    mixing = round(st_mix_lognormal_tnorm$par$estimate["prob"], 2),
    mean = round(st_mix_lognormal_tnorm$par$estimate["mean"], 2),
    sd = round(st_mix_lognormal_tnorm$par$estimate["sd"], 2)
  )
)

save(parameter_distributions, file = "../data/priors_non_clinical.RData")
```


```{r print tables, echo=FALSE, message=FALSE, warning=FALSE}
drift_compare
colnames(drift_compare) <- c("Distribution Function", "AIC", "wAIC")
boundary_compare
colnames(boundary_compare) <- c("Distribution Function", "AIC", "wAIC")
mirrored_bias_compare
colnames(mirrored_bias_compare) <- c("Distribution Function", "AIC", "wAIC")
ter_compare
colnames(ter_compare) <- c("Distribution Function", "AIC", "wAIC")
sv_compare
colnames(sv_compare) <- c("Distribution Function", "AIC", "wAIC")
relative_sz_compare
colnames(relative_sz_compare) <- c("Distribution Function", "AIC", "wAIC")
ster_compare
colnames(ster_compare) <- c("Distribution Function", "AIC", "wAIC")

```

```{r Prior Plots, message=FALSE, warning=FALSE, include=FALSE}
postscript(file = "../plots/DDM_Priors_non_clinical.eps", onefile = TRUE, horizontal = FALSE,
           width = 11, height = 11)
par(mfrow = c (4, 2))
#layout(matrix(c(1,2,3,4, 5, 6, 7, 7), 4, 2, byrow = TRUE))
# v
par(cex.main = 1.5, mar = c(5, 6, 4, 5) + 0.1, mgp = c(3.5, 1, 0), cex.lab = 2 ,
    font.lab = 1.5, cex.axis = 1.8, bty = "n", las = 1.5)
h <- hist(abs(v$v), freq = FALSE, main = "", xlab = "", ylab = " Density",
          ylim = c(0, 0.4),
          xlim = c(0, 15), axes = FALSE, col = "grey", breaks = 40)
axis(1, seq(0, 15, by = 5))
axis(2, seq(0, 0.4, by = .1))
rug(abs(v$v))
mtext(paste("v (N = ", length(v$v), ")", sep = ""),
      side = 1, line = 4, cex = 1.7, font = 1)
curve(dgamma(x, shape = parameter_distributions$v$shape,
          rate = parameter_distributions$v$rate)*parameter_distributions$v$mixing,
      col = "#E31A1C", lwd = 3, add=T)
# add mixture component in black
curve(dgamma(x, shape = drift_mix_gamma$par$estimate["shape1"],
            rate = drift_mix_gamma$par$estimate["rate1"])*(1-parameter_distributions$v$mixing),
      col = "black", lwd = 1.5, add = TRUE)


# a
par(cex.main = 1.5, mar = c(5, 6, 4, 5) + 0.1, mgp = c(3.5, 1, 0), cex.lab = 2 ,
    font.lab = 1.5, cex.axis = 1.8, bty = "n", las = 1.5)
h <- hist(a$a, freq = FALSE, main = "", xlab = "", ylab = " Density",
          ylim = c(0, 1),
          xlim = c(0, 7), axes = FALSE, col = "grey", breaks = 60)
axis(1, seq(0, 7, by = 1))
axis(2, seq(0, 1, by = 0.5))
rug(a$a)
mtext(paste("a (N = ", length(a$a), ")", sep = ""),
      side = 1, line = 4, cex = 1.7, font = 1)
curve(dtnorm(x, parameter_distributions$a$mean, parameter_distributions$a$sd, lower = 0)*(1-parameter_distributions$a$mixing),
      col = "#E31A1C", lwd = 3, add = TRUE)
# add mixture component in black
curve(dlnorm(x, boundary_mix_lognormal_tnorm$par$estimate["meanlog"],
             boundary_mix_lognormal_tnorm$par$estimate["sdlog"])*parameter_distributions$a$mixing,
      col = "black", lwd = 1.5, add = TRUE)


# Mirrored zr
par(cex.main = 1.5, mar = c(5, 6, 4, 5) + 0.1, mgp = c(3.5, 1, 0), cex.lab = 2 ,
    font.lab = 1.5, cex.axis = 1.8, bty = "n", las = 1.5)
h <- hist(zr_mirrored, freq = FALSE, main = "", xlab = "", ylab = " Density",
          ylim = c(0, 10),
          xlim = c(0, 1), axes = FALSE, col = "grey", breaks = 20)
axis(1, seq(0, 1, by = .25))
axis(2, seq(0, 10, by = 2))
rug(zr_mirrored)
mtext(paste("Mirrored zr  (N = ", nrow(zr), ")", sep = ""),
      side = 1, line = 4, cex = 1.7, font = 1)
curve(dtt(x, location =  parameter_distributions$zr_mirrored$location,
          parameter_distributions$zr_mirrored$scale,
          df = parameter_distributions$zr_mirrored$df, lower = 0, upper = 1),
      col = "#E31A1C", lwd = 3, add = TRUE)

# Ter
par(cex.main = 1.5, mar = c(5, 6, 4, 5) + 0.1, mgp = c(3.5, 1, 0), cex.lab = 2 ,
    font.lab = 1.5, cex.axis = 1.8, bty = "n", las = 1.5)
h <- hist(ter$ter, freq = FALSE, main = "", xlab = "", ylab = " Density",
          ylim = c(0, 4),
          xlim = c(0, 4), axes = FALSE, col = "grey", breaks = 50)
axis(1, seq(0, 4, by = 1))
axis(2, seq(0, 4, by = 1))
rug(ter$ter)
mtext(expression(paste(T[er], " (N = 718)", sep = "")),
      side = 1, line = 4, cex = 1.7, font = 1)
curve(dgamma(x, parameter_distributions$ter$shape,
          rate=parameter_distributions$ter$rate)*(1-parameter_distributions$ter$mixing),
      col = "#E31A1C", lwd = 3, add = TRUE)
# add mixture component in black
curve(dgamma(x, ter_mix_gamma$par$estimate["shape"],
             rate = ter_mix_gamma$par$estimate["rate"])*parameter_distributions$ter$mixing,
      col = "black", lwd = 1.5, add = TRUE)

# sv
par(cex.main = 1.5, mar = c(5, 6, 4, 5) + 0.1, mgp = c(3.5, 1, 0), cex.lab = 2 ,
    font.lab = 1.5, cex.axis = 1.8, bty = "n", las = 1.5)
h <- hist(sv$sv, freq = FALSE, main = "", xlab = "", ylab = " Density",
          ylim = c(0, 0.6), xlim = c(0, 4), col = "grey", breaks = 20)
axis(1, seq(0, 4, by = 1))
axis(2, seq(0, 0.6, by = 0.2))
rug(sv$sv)
mtext(expression(paste(s[v], " (N = 282)", sep = "")),
      side = 1, line = 4, cex = 1.7, font = 1)
curve(dtnorm(x, parameter_distributions$sv$mean, parameter_distributions$sv$sd, lower = 0)*(1-parameter_distributions$sv$mixing),
      col = "#E31A1C", lwd = 3, add=T)
# add mixture component in black
curve(dgamma(x, sv_mix_gamma_tnorm$par$estimate["shape"],
             rate= sv_mix_gamma_tnorm$par$estimate["rate"])*parameter_distributions$sv$mixing,
      col = "black", lwd = 1.5, add = TRUE)

# relative sz
par(cex.main = 1.5, mar = c(5, 6, 4, 5) + 0.1, mgp = c(3.5, 1, 0), cex.lab = 2 ,
    font.lab = 1.5, cex.axis = 1.8, bty = "n", las = 1.5)
h <- hist(sz_relative$sz_relative, freq = FALSE, main = "", xlab = "", ylab = " Density",
          ylim = c(0, 3),
          xlim = c(0, 1), axes = FALSE, col = "grey", breaks = 30)
axis(1, seq(0, 2, by = 1))
axis(2, seq(0, 3, by = 1))
rug(sz_relative$sz_relative)
mtext(expression(paste("Relative ", s[z], " (N = 248)", sep = "")),
      side = 1, line = 4, cex = 1.7, font = 1)
curve(dtnorm(x, parameter_distributions$relative_sz$mean,
             parameter_distributions$relative_sz$sd, lower = 0, upper = 1),
      col = "#E31A1C", lwd = 3, add=T)

# ster
par(cex.main = 1.5, mar = c(5, 6, 4, 5) + 0.1, mgp = c(3.5, 1, 0), cex.lab = 2,
    font.lab = 1.5, cex.axis = 1.8, bty = "n", las = 1.5)
h <- hist(ster$ster, freq = FALSE, main = "", xlab = "", ylab = " Density",
          ylim = c(0, 8),
          xlim = c(0, 5), axes = FALSE, col = "grey", breaks = 100)
axis(1, seq(0, 5, by = 1))
axis(2, seq(0, 8, by = 2))
rug(ster$ster)
mtext(expression(paste(s[T][er], " (N = 318)", sep = "")),
      side = 1, line = 4, cex = 1.7, font = 1)
curve(dtnorm(x, parameter_distributions$ster$mean,
          parameter_distributions$ster$sd, lower = 0, upper = Inf)*(1-parameter_distributions$ster$mixing),
      col = "#E31A1C", lwd = 3, add=T)
# add mixture component in black
curve(dlnorm(x, st_mix_lognormal_tnorm$par$estimate["meanlog"],
             st_mix_lognormal_tnorm$par$estimate["sdlog"])*parameter_distributions$ster$mixing,
      col = "black", lwd = 1.5, add = TRUE)


dev.off()
```




